/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* AdvertisementType tells us how a device is advertising. Bluetooth-specific */
typedef enum _AdvertisementType {
    AdvertisementType_BLE_ADVERTISEMENT = 0
} AdvertisementType;

/* DetectionCriteria describes why we think this is a valid detection. Bluetooth & WIFI */
typedef enum _DetectionCriteria {
    DetectionCriteria_MAC_ONLY = 0,
    DetectionCriteria_NAME_AND_MAC = 1,
    DetectionCriteria_NAME_ONLY = 2,
    DetectionCriteria_SSID_AND_MAC = 3,
    DetectionCriteria_SSID_ONLY = 4
} DetectionCriteria;

/* DeviceCategory tells us what type of device we're detecting */
typedef enum _DeviceCategory {
    DeviceCategory_FLOCK_SAFETY = 0
} DeviceCategory;

typedef enum _FrameType {
    FrameType_BEACON = 0,
    FrameType_PROBE_REQUEST = 1
} FrameType;

typedef enum _HighMedLow {
    HighMedLow_HIGH = 0,
    HighMedLow_MED = 1,
    HighMedLow_LOW = 2
} HighMedLow;

typedef enum _Protocol {
    Protocol_BLUETOOTH_LE = 0,
    Protocol_WIFI = 1
} Protocol;

typedef enum _PrimaryIndicator {
    PrimaryIndicator_DEVICE_NAME = 0,
    PrimaryIndicator_MAC_ADDRESS = 1
} PrimaryIndicator;

typedef enum _SignalStrength {
    SignalStrength_MEDIUM = 0,
    SignalStrength_STRONG = 1,
    SignalStrength_WEAK = 2
} SignalStrength;

/* Struct definitions */
typedef struct _BleDetection {
    /* 64bit fields */
    uint64_t timestamp;
    /* 32bit fields */
    uint32_t device_name_length;
    int32_t rssi;
    uint32_t threat_score;
    /* Enum fields */
    AdvertisementType advertisement_type;
    HighMedLow alert_level;
    HighMedLow mac_match_confidence;
    HighMedLow name_match_confidence;
    DetectionCriteria detection_criteria;
    DeviceCategory device_category;
    PrimaryIndicator primary_indicator;
    Protocol protocol;
    SignalStrength signal_strength;
    /* string fields */
    pb_callback_t detection_time;
    pb_callback_t detection_method;
    pb_callback_t mac_address;
    pb_callback_t device_name;
    pb_callback_t mac_prefix;
    pb_callback_t vendor_oui;
    pb_callback_t matched_mac_pattern;
    pb_callback_t matched_name_pattern;
    pb_callback_t advertisement_description;
    pb_callback_t detection_reason;
    /* bool fields */
    bool has_device_name;
} BleDetection;

typedef struct _WifiDetection {
    /* 64bit fields */
    uint64_t timestamp;
    /* 32bit fields */
    uint32_t ssid_length;
    int32_t rssi;
    uint32_t channel;
    uint32_t threat_score;
    /* Enum fields */
    Protocol protocol;
    HighMedLow alert_level;
    DeviceCategory device_category;
    SignalStrength signal_strength;
    HighMedLow ssid_match_confidence;
    HighMedLow mac_match_confidence;
    DetectionCriteria detection_criteria;
    FrameType frame_type;
    /* string fields */
    pb_callback_t detection_time;
    pb_callback_t detection_method;
    pb_callback_t ssid;
    pb_callback_t mac_address;
    pb_callback_t mac_prefix;
    pb_callback_t vendor_oui;
    pb_callback_t matched_ssid_pattern;
    pb_callback_t matched_mac_pattern;
    pb_callback_t frame_description;
} WifiDetection;

/* Payload Encapsulation so that we don't have to guess what we're decoding client-side */
typedef struct _PayloadEncapsulation {
    uint32_t frame_id;
    Protocol payload_type;
    pb_callback_t payload_data;
} PayloadEncapsulation;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _AdvertisementType_MIN AdvertisementType_BLE_ADVERTISEMENT
#define _AdvertisementType_MAX AdvertisementType_BLE_ADVERTISEMENT
#define _AdvertisementType_ARRAYSIZE ((AdvertisementType)(AdvertisementType_BLE_ADVERTISEMENT+1))

#define _DetectionCriteria_MIN DetectionCriteria_MAC_ONLY
#define _DetectionCriteria_MAX DetectionCriteria_SSID_ONLY
#define _DetectionCriteria_ARRAYSIZE ((DetectionCriteria)(DetectionCriteria_SSID_ONLY+1))

#define _DeviceCategory_MIN DeviceCategory_FLOCK_SAFETY
#define _DeviceCategory_MAX DeviceCategory_FLOCK_SAFETY
#define _DeviceCategory_ARRAYSIZE ((DeviceCategory)(DeviceCategory_FLOCK_SAFETY+1))

#define _FrameType_MIN FrameType_BEACON
#define _FrameType_MAX FrameType_PROBE_REQUEST
#define _FrameType_ARRAYSIZE ((FrameType)(FrameType_PROBE_REQUEST+1))

#define _HighMedLow_MIN HighMedLow_HIGH
#define _HighMedLow_MAX HighMedLow_LOW
#define _HighMedLow_ARRAYSIZE ((HighMedLow)(HighMedLow_LOW+1))

#define _Protocol_MIN Protocol_BLUETOOTH_LE
#define _Protocol_MAX Protocol_WIFI
#define _Protocol_ARRAYSIZE ((Protocol)(Protocol_WIFI+1))

#define _PrimaryIndicator_MIN PrimaryIndicator_DEVICE_NAME
#define _PrimaryIndicator_MAX PrimaryIndicator_MAC_ADDRESS
#define _PrimaryIndicator_ARRAYSIZE ((PrimaryIndicator)(PrimaryIndicator_MAC_ADDRESS+1))

#define _SignalStrength_MIN SignalStrength_MEDIUM
#define _SignalStrength_MAX SignalStrength_WEAK
#define _SignalStrength_ARRAYSIZE ((SignalStrength)(SignalStrength_WEAK+1))

#define BleDetection_advertisement_type_ENUMTYPE AdvertisementType
#define BleDetection_alert_level_ENUMTYPE HighMedLow
#define BleDetection_mac_match_confidence_ENUMTYPE HighMedLow
#define BleDetection_name_match_confidence_ENUMTYPE HighMedLow
#define BleDetection_detection_criteria_ENUMTYPE DetectionCriteria
#define BleDetection_device_category_ENUMTYPE DeviceCategory
#define BleDetection_primary_indicator_ENUMTYPE PrimaryIndicator
#define BleDetection_protocol_ENUMTYPE Protocol
#define BleDetection_signal_strength_ENUMTYPE SignalStrength

#define WifiDetection_protocol_ENUMTYPE Protocol
#define WifiDetection_alert_level_ENUMTYPE HighMedLow
#define WifiDetection_device_category_ENUMTYPE DeviceCategory
#define WifiDetection_signal_strength_ENUMTYPE SignalStrength
#define WifiDetection_ssid_match_confidence_ENUMTYPE HighMedLow
#define WifiDetection_mac_match_confidence_ENUMTYPE HighMedLow
#define WifiDetection_detection_criteria_ENUMTYPE DetectionCriteria
#define WifiDetection_frame_type_ENUMTYPE FrameType

#define PayloadEncapsulation_payload_type_ENUMTYPE Protocol


/* Initializer values for message structs */
#define BleDetection_init_default                {0, 0, 0, 0, _AdvertisementType_MIN, _HighMedLow_MIN, _HighMedLow_MIN, _HighMedLow_MIN, _DetectionCriteria_MIN, _DeviceCategory_MIN, _PrimaryIndicator_MIN, _Protocol_MIN, _SignalStrength_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define WifiDetection_init_default               {0, 0, 0, 0, 0, _Protocol_MIN, _HighMedLow_MIN, _DeviceCategory_MIN, _SignalStrength_MIN, _HighMedLow_MIN, _HighMedLow_MIN, _DetectionCriteria_MIN, _FrameType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define PayloadEncapsulation_init_default        {0, _Protocol_MIN, {{NULL}, NULL}}
#define BleDetection_init_zero                   {0, 0, 0, 0, _AdvertisementType_MIN, _HighMedLow_MIN, _HighMedLow_MIN, _HighMedLow_MIN, _DetectionCriteria_MIN, _DeviceCategory_MIN, _PrimaryIndicator_MIN, _Protocol_MIN, _SignalStrength_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0}
#define WifiDetection_init_zero                  {0, 0, 0, 0, 0, _Protocol_MIN, _HighMedLow_MIN, _DeviceCategory_MIN, _SignalStrength_MIN, _HighMedLow_MIN, _HighMedLow_MIN, _DetectionCriteria_MIN, _FrameType_MIN, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define PayloadEncapsulation_init_zero           {0, _Protocol_MIN, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define BleDetection_timestamp_tag               1
#define BleDetection_device_name_length_tag      10
#define BleDetection_rssi_tag                    11
#define BleDetection_threat_score_tag            12
#define BleDetection_advertisement_type_tag      20
#define BleDetection_alert_level_tag             21
#define BleDetection_mac_match_confidence_tag    22
#define BleDetection_name_match_confidence_tag   23
#define BleDetection_detection_criteria_tag      24
#define BleDetection_device_category_tag         25
#define BleDetection_primary_indicator_tag       26
#define BleDetection_protocol_tag                27
#define BleDetection_signal_strength_tag         28
#define BleDetection_detection_time_tag          50
#define BleDetection_detection_method_tag        51
#define BleDetection_mac_address_tag             52
#define BleDetection_device_name_tag             53
#define BleDetection_mac_prefix_tag              54
#define BleDetection_vendor_oui_tag              55
#define BleDetection_matched_mac_pattern_tag     56
#define BleDetection_matched_name_pattern_tag    57
#define BleDetection_advertisement_description_tag 58
#define BleDetection_detection_reason_tag        59
#define BleDetection_has_device_name_tag         80
#define WifiDetection_timestamp_tag              1
#define WifiDetection_ssid_length_tag            10
#define WifiDetection_rssi_tag                   11
#define WifiDetection_channel_tag                12
#define WifiDetection_threat_score_tag           13
#define WifiDetection_protocol_tag               20
#define WifiDetection_alert_level_tag            21
#define WifiDetection_device_category_tag        22
#define WifiDetection_signal_strength_tag        23
#define WifiDetection_ssid_match_confidence_tag  24
#define WifiDetection_mac_match_confidence_tag   25
#define WifiDetection_detection_criteria_tag     26
#define WifiDetection_frame_type_tag             27
#define WifiDetection_detection_time_tag         50
#define WifiDetection_detection_method_tag       51
#define WifiDetection_ssid_tag                   52
#define WifiDetection_mac_address_tag            53
#define WifiDetection_mac_prefix_tag             54
#define WifiDetection_vendor_oui_tag             55
#define WifiDetection_matched_ssid_pattern_tag   56
#define WifiDetection_matched_mac_pattern_tag    57
#define WifiDetection_frame_description_tag      58
#define PayloadEncapsulation_frame_id_tag        1
#define PayloadEncapsulation_payload_type_tag    5
#define PayloadEncapsulation_payload_data_tag    10

/* Struct field encoding specification for nanopb */
#define BleDetection_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   device_name_length,  10) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,             11) \
X(a, STATIC,   SINGULAR, UINT32,   threat_score,     12) \
X(a, STATIC,   SINGULAR, UENUM,    advertisement_type,  20) \
X(a, STATIC,   SINGULAR, UENUM,    alert_level,      21) \
X(a, STATIC,   SINGULAR, UENUM,    mac_match_confidence,  22) \
X(a, STATIC,   SINGULAR, UENUM,    name_match_confidence,  23) \
X(a, STATIC,   SINGULAR, UENUM,    detection_criteria,  24) \
X(a, STATIC,   SINGULAR, UENUM,    device_category,  25) \
X(a, STATIC,   SINGULAR, UENUM,    primary_indicator,  26) \
X(a, STATIC,   SINGULAR, UENUM,    protocol,         27) \
X(a, STATIC,   SINGULAR, UENUM,    signal_strength,  28) \
X(a, CALLBACK, SINGULAR, STRING,   detection_time,   50) \
X(a, CALLBACK, SINGULAR, STRING,   detection_method,  51) \
X(a, CALLBACK, SINGULAR, STRING,   mac_address,      52) \
X(a, CALLBACK, SINGULAR, STRING,   device_name,      53) \
X(a, CALLBACK, SINGULAR, STRING,   mac_prefix,       54) \
X(a, CALLBACK, SINGULAR, STRING,   vendor_oui,       55) \
X(a, CALLBACK, SINGULAR, STRING,   matched_mac_pattern,  56) \
X(a, CALLBACK, SINGULAR, STRING,   matched_name_pattern,  57) \
X(a, CALLBACK, SINGULAR, STRING,   advertisement_description,  58) \
X(a, CALLBACK, SINGULAR, STRING,   detection_reason,  59) \
X(a, STATIC,   SINGULAR, BOOL,     has_device_name,  80)
#define BleDetection_CALLBACK pb_default_field_callback
#define BleDetection_DEFAULT NULL

#define WifiDetection_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, STATIC,   SINGULAR, UINT32,   ssid_length,      10) \
X(a, STATIC,   SINGULAR, SINT32,   rssi,             11) \
X(a, STATIC,   SINGULAR, UINT32,   channel,          12) \
X(a, STATIC,   SINGULAR, UINT32,   threat_score,     13) \
X(a, STATIC,   SINGULAR, UENUM,    protocol,         20) \
X(a, STATIC,   SINGULAR, UENUM,    alert_level,      21) \
X(a, STATIC,   SINGULAR, UENUM,    device_category,  22) \
X(a, STATIC,   SINGULAR, UENUM,    signal_strength,  23) \
X(a, STATIC,   SINGULAR, UENUM,    ssid_match_confidence,  24) \
X(a, STATIC,   SINGULAR, UENUM,    mac_match_confidence,  25) \
X(a, STATIC,   SINGULAR, UENUM,    detection_criteria,  26) \
X(a, STATIC,   SINGULAR, UENUM,    frame_type,       27) \
X(a, CALLBACK, SINGULAR, STRING,   detection_time,   50) \
X(a, CALLBACK, SINGULAR, STRING,   detection_method,  51) \
X(a, CALLBACK, SINGULAR, STRING,   ssid,             52) \
X(a, CALLBACK, SINGULAR, STRING,   mac_address,      53) \
X(a, CALLBACK, SINGULAR, STRING,   mac_prefix,       54) \
X(a, CALLBACK, SINGULAR, STRING,   vendor_oui,       55) \
X(a, CALLBACK, SINGULAR, STRING,   matched_ssid_pattern,  56) \
X(a, CALLBACK, SINGULAR, STRING,   matched_mac_pattern,  57) \
X(a, CALLBACK, SINGULAR, STRING,   frame_description,  58)
#define WifiDetection_CALLBACK pb_default_field_callback
#define WifiDetection_DEFAULT NULL

#define PayloadEncapsulation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   frame_id,          1) \
X(a, STATIC,   SINGULAR, UENUM,    payload_type,      5) \
X(a, CALLBACK, SINGULAR, BYTES,    payload_data,     10)
#define PayloadEncapsulation_CALLBACK pb_default_field_callback
#define PayloadEncapsulation_DEFAULT NULL

extern const pb_msgdesc_t BleDetection_msg;
extern const pb_msgdesc_t WifiDetection_msg;
extern const pb_msgdesc_t PayloadEncapsulation_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define BleDetection_fields &BleDetection_msg
#define WifiDetection_fields &WifiDetection_msg
#define PayloadEncapsulation_fields &PayloadEncapsulation_msg

/* Maximum encoded size of messages (where known) */
/* BleDetection_size depends on runtime parameters */
/* WifiDetection_size depends on runtime parameters */
/* PayloadEncapsulation_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
